
services:

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    depends_on:
      - frontend
      - user-management
      - pong
    networks:
      - transcendence-network
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # This ensures Vite listens on all network interfaces inside the container
    command: npm run dev -- --host
    networks:
      - transcendence-network

  user-management:
    build: ./user-management
    container_name: user-management
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - transcendence-network

  pong:
    build: ./pong
    container_name: pong
    ports:
      - "3002:3002"
    networks:
      - transcendence-network

networks:
  transcendence-network:
    driver: bridge