services:
  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/dev.db:/app/dev.db
      - ./backend/avatars:/app/avatars
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./logs:/app/logs
    environment:
      - CHOKIDAR_USEPOLLING=true 
    command: sh -c "npm run dev -- --host 0.0.0.0 | tee /app/logs/frontend.log"

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - ./nginx/certs:/etc/nginx/certs
  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile
      target: builder
    expose:
      - "3000"
    volumes:
      - ./chat:/app
      - /app/node_modules
      - ./logs:/app/logs
    command: npm run dev

  games:
    build:
      context: ./games
      dockerfile: Dockerfile
    volumes:
      - ./shared:/app/shared
      - ./logs:/app/logs
      - ./games:/app/games
      - /app/games/node_modules
    command: npm run dev