services:
  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/dev.db:/app/dev.db
      - ./backend/avatars:/app/avatars
    command: npm run dev

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true 
    command: npm run dev -- --host 0.0.0.0

  nginx:
    volumes:
      - ./ngnix/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
      - ./ngnix/certs:/etc/nginx/certs:ro
  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile
      target: builder
    expose:
      - "3000"
    volumes:
      - ./chat:/app
      - /app/node_modules
    command: npm run dev