volumes:
  esdata01:
    driver: local
  kibanadata:
    driver: local
  logstashdata01:
    driver: local


networks:
  elastic:
    driver: bridge


services:
 
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - elastic
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./logs:/var/log/nginx
      - ./nginx/certs:/etc/nginx/certs
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - elastic
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_ACCESS_SECRET}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - SALT_ROUNDS=${SALT_ROUNDS}
      - GOOGLE_OAUTH_ID=${GOOGLE_OAUTH_ID}
      - AVATARS_STORAGE_PATH=${AVATARS_STORAGE_PATH}
      - GOOGLE_OAUTH_SECRET=${GOOGLE_OAUTH_SECRET}
      - GITHUB_OAUTH_ID=${GITHUB_OAUTH_ID}
      - GITHUB_OAUTH_SECRET=${GITHUB_OAUTH_SECRET}
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./backend/avatars:/app/avatars
      - ./backend/dev.db:/app/dev.db
      - ./logs:/app/logs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - elastic
    volumes:
      - ./shared:/app/shared
      - ./logs:/app/logs
    depends_on:
      - backend
  
  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile
    networks:
      - elastic
    environment:
      - PORT=3000
      - BACKEND_URL=http://backend:3000
      - INTERNAL_API_SECRET=${INTERNAL_API_SECRET}
      - JWT_SECRET=${JWT_ACCESS_SECRET}
    volumes:
      - ./logs:/app/logs
    depends_on:
      - backend

  games:
    build:
      context: ./games
      dockerfile: Dockerfile
    networks:
      - elastic
    environment:
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
    volumes:
      - ./shared:/app/shared
      - ./logs:/app/logs